os : osx
osx_image: xcode9.3
compiler: clang
language: cpp
cache: 
  directories:
    - $HOME/Library/Caches/Homebrew
before_script:
  - java -version
  - brew tap facebook/fb
  - brew install buck
  - buck --version
script:
  - buck test --all
