os:
  - osx
osx_image: xcode9.2
language:
  - cpp
compiler:
  - clang
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_script:
  - brew tap facebook/fb
  - brew install buck watchman
  - buck --version
  - java -version
script:
  - buck test --all